app:
  name: ticket
  ip: 0.0.0.0
  port: 8041
  mode: debug

#华为-Mysql
#db:
#  name:         ticket
#  host:         120.46.48.255
#  user:         root
#  password:     root
#  port:         3306

#腾讯云-Mysql
db:
  name:         ticket
  host:         82.157.206.194
  user:         root
  password:     Sdl@admin
  port:         3306

#华为-redis
#redis:
#  host:         120.46.48.255
#  port:         6379
#  password:     ""

redis:
  host:         82.157.206.194
  port:         6379
  password:     "root"
jwt:
  signing-key: root
  expires-time: 7d
  buffer-time: 1d
  issuer: admin

#验证码
digitDriver:
  height: 50
  width: 200
#验证码长度
  length: 4
#背景的点数，越大，字体越模糊
  dot-count: 1
# 过期时间-分钟
  expire-time: 2